-- =============================================================================
-- FlexFit – Base Schema
-- File: backend/schema/base_schema.sql
-- Purpose: Full baseline schema for fresh installs and new environment setup.
--          Run this once against an empty database before applying migrations.
--
-- Usage:
--   mysql -u <user> -p <database> < backend/schema/base_schema.sql
--
-- Notes:
--   - All CREATE TABLE statements use IF NOT EXISTS for idempotency.
--   - After running base_schema.sql, run seed_data.sql to populate lookups.
--   - Then apply all numbered migrations from backend/migrations/**/.
-- =============================================================================

-- Placeholder: add full table definitions here as the project matures.
-- For the current working schema, refer to:
--   backend/schema/exercises_schema.sql
--   backend/schema/workout_schedule_schema.sql
--
-- And run migrations in order from backend/migrations/.
