-- =============================================================================
-- FlexFit v0.82.21 – Dashboard Metric Integration
-- Migration: 0.82.21_dashboard_metrics.sql
-- Date: 2026-05-26
--
-- Documents the three live metric queries used by GET /api/dashboard/metrics.
-- No schema changes required beyond those added in 0.82.20.
-- Run 0.82.20_dashboard_metrics.sql first to ensure indexes exist.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Query 1: Workouts in selected date range (completed sessions)
-- ---------------------------------------------------------------------------
-- SELECT COUNT(*) AS cnt
-- FROM workout_log_sessions
-- WHERE user_id     = :userId
--   AND status      = 'completed'
--   AND workout_date BETWEEN :startDate AND :endDate;

-- Prior period (same length, shifted back) for +/- comparison:
-- SELECT COUNT(*) AS cnt
-- FROM workout_log_sessions
-- WHERE user_id     = :userId
--   AND status      = 'completed'
--   AND workout_date BETWEEN :priorStart AND :priorEnd;

-- ---------------------------------------------------------------------------
-- Query 2: Current streak (global – not date-range bound)
-- ---------------------------------------------------------------------------
-- SELECT DISTINCT DATE_FORMAT(workout_date, '%Y-%m-%d') AS d
-- FROM workout_log_sessions
-- WHERE user_id = :userId AND status = 'completed'
-- ORDER BY d DESC
-- LIMIT 365;
-- (streak calculated in StreakCalculator.js)

-- ---------------------------------------------------------------------------
-- Query 3: Calories burned (all workout types, selected date range)
-- ---------------------------------------------------------------------------
-- SELECT COALESCE(SUM(Calories), 0) AS total
-- FROM workout_log
-- WHERE UserID     = :userId
--   AND WorkoutDate BETWEEN :startDate AND :endDate;

-- ---------------------------------------------------------------------------
-- Query 4: Weekly target from user's active workout schedule
-- ---------------------------------------------------------------------------
-- SELECT COUNT(*) AS cnt
-- FROM workout_schedule_groups
-- WHERE workout_schedule_id = (
--   SELECT id FROM workout_schedules
--   WHERE user_id = :userId AND status = 'active'
--   ORDER BY updated_at DESC
--   LIMIT 1
-- );

-- ---------------------------------------------------------------------------
-- Index verification (no new indexes needed beyond 0.82.20)
-- ---------------------------------------------------------------------------
-- SHOW INDEX FROM workout_log_sessions WHERE Key_name = 'idx_wls_user_status_date';
-- SHOW INDEX FROM workout_log WHERE Key_name = 'idx_wl_user_type_date';
-- SHOW INDEX FROM workout_schedule_groups WHERE Key_name = 'idx_wsg_schedule';
