-- =============================================================================
-- FlexFit – Lookup Tables
-- File: backend/schema/lookup_tables.sql
-- Purpose: Reference/lookup tables shared across features.
--          Includes exercise categories, muscle groups, equipment types,
--          workout types, and other enumerated domain values.
--
-- Safe to run multiple times – all statements use CREATE TABLE IF NOT EXISTS.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Placeholder: Formalize lookup tables here as the domain model matures.
-- Examples:
--   - exercise_categories
--   - muscle_groups
--   - equipment_types
--   - workout_types
-- ---------------------------------------------------------------------------
